config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/home/about" => "homes#about"
  resources :books, only: [:edit, :index, :show, :create, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

##空ではないバリテーショション
  validates :title, presence: true
  validates :body, presence: true
##内容分200文字以下のﾊﾞﾘﾃｰｼｮﾝ
  validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


validates :introduction, length: { maximum: 50 }
validates :name, uniqueness: true
validates :name, length: { in: 2..20 }

##-------------------------------------------------------------------------------------------------------
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
##-------------------------------------------------------------------------------------------------------

##-------------------------------------------------------------------------------------------------------
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
##-------------------------------------------------------------------------------------------------------


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
##--------------------------------------------------------------------------
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
  
  
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
##--------------------------------------------------------------------------

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new = Book.new
    @user = @book.user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
    redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully.."
        redirect_to book_path(@book.id)
      else
        render :edit
      end
  end



  private


  def book_params
    params.require(:book).permit(:title, :body)
  end

  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end
  
  def about
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id]) 
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
    redirect_to user_path(current_user.id)
    end
  end
  
  def update
    user = User.find(params[:id])
    unless user.id == current_user.id
    redirect_to books_path
    end
   
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully.."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2>New book</h2>
<%= form_with model: book do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion </h4>
  <%= f.text_area :body %>
  <div class="text"> 
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <p><%= f.submit 'Update Book' %></p>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      <span>|</span>
      <a href="/books">Back</a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<!-- books index -->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <!-- 投稿画面-->
      <%= render 'form', book: @book %>
    </div>


    <div class="col-md-8 offset-md-1">
    <!-- すべてのユーザーの投稿一覧 -->
      <h1>Books</h1>
      <table class="table">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <td><%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
          <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tbody>
          <td><%= link_to user_path(@book.user.id) do %><%= image_tag @book.user.get_profile_image(100,100) %><% end %>
          <p><%= link_to user_path(@book.user.id) do %><%= @book.user.name %><% end %></p>
          </td>
          <td><%= link_to book_path(@book.id) do %><%= @book.title %><% end %></td>
          <td><%= @book.body %></td>
          <td>
          <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
          <% end %>
          </td>
          <td>
          <% if @book.user == current_user %>
            <%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger" , method: :delete %>
          <% end %>
          </td>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to <strong><i class="fa-solid fa-book"></i>Bookers</strong>!!</h1>
    </div>
   </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container mt-5">
  <div class="row">
    <div class="mx-auto">

      <h1>welcome to <strong><i class="fa-solid fa-book"></i>Bookers</strong>!!</h1>
      <p>In<strong><i class="fa-solid fa-book"></i>Bookers</strong>,</p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %></p>
      <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %></p>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/44ed4822dd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    
  <%= link_to "Bookers", root_path %>
    
    
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
    <li><%= link_to user_path(current_user.id) do %><i class="fa-solid fa-house"></i>Home<% end %></li>
    <li><%= link_to users_path do %><i class="fa-solid fa-users"></i>Users<% end %></li>
    <li><%= link_to books_path do %><i class="fa-solid fa-book-open"></i>Books<% end %></li>
    <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa-solid fa-right-from-bracket"></i>Log out<% end %></li>
    
    <% else %>
    <li><%= link_to root_path do %><i class="fa-solid fa-house"></i>Home<% end %>
    <li><%= link_to home_about_path do %><i class="fa-solid fa-link"></i>About<% end %>
    <li><%= link_to new_user_registration_path do %><i class="fa-solid fa-user-plus"></i>Sign up<% end %>
    <li><%= link_to new_user_session_path do %><i class="fa-solid fa-right-to-bracket"></i>Log in<% end %>
    <li><% end %>
  </ul>
    
    </div>
    </nav>
    </header> 
    
    
    <%= yield %>
  
  <footer>
  <div class="container mt-5">
  <div class="row">
  <div class="mx-auto">
  <p>CopyRight Infratop.inc</p>
  </div>
  </div>
  </div>
  </footer>
  
  </body>
</html>

app/views/users/_info.html.erb
<h1>User info</h1>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user.id),class: "btn btn-outline-secondary btn-block" do %><i class="fa-solid fa-user-gear"></i><% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>User info</h1>
      <% if @user.errors.any? %>
      <%= @user.errors.count %>errors prohibited this obj from being saved:
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
        <p>Name</p>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:""%>
        <p>Image</p>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
        <p>Introduction</p>
        <%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:""%>
        <div class="text"> 
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
          <th>image</th>
          <th>name</th>
  　       <th></th>
  　       </tr>
        </thead>
   
        <tbody>
          <% @users.each do |user| %>
          <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id)%></td>
  　       </tr>
          <% end %>
        </tbody>
   
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <td><%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %></td>
          <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
        </tbody>
        <% end %>
      </table>
  
    </div>

  </div>
</div>